### ISSUE TITLE
Shorebird is not initialized. Did you run "shorebird init"?

### ISSUE THREAD

**Issue by Djsmk123** [shorebirdtech/setup-shorebird#8]
I am following this [https://docs.shorebird.dev/ci/github](https://docs.shorebird.dev/ci/github) to integrate github action.

Everything work on local but when I start github action  getting this error

![Screenshot 2023-08-04 141048](https://github.com/shorebirdtech/setup-shorebird/assets/74850678/17117fd5-9f9b-4de2-a460-686773c58a6d)

- [x] Added token in github secert.

## Script
```
name: Shorebird Workflow

on:
  push:
    branches: [main]

jobs:
  patch-application:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v0
      - name: 🚀 Use Shorebird
        run: shorebird --version

       # for testing purposes

      - name: 🚀 Check Application
        run: shorebird apps list
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

       # for testing purposes
      - name: 🚀 Shorebird doctor
        run: shorebird doctor --fix
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

      - name: 🚀 Shorebird Patch
        run: shorebird patch android --force
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
```
